---
swagger: "2.0"
info:
  description: This is a simple API.
  version: v1
  title: Simple Identity API
  contact:
    email: vathakur@deloitte.com.au
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /Deloitte368/Identity/1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /identities:
    get:
      description: |
        this is a sample get operation
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: this is a sample response
          schema:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
    post:
      description: |
        this is a sample post operation
      parameters: []
      responses:
        201:
          description: OK
        400:
          description: Bad_Request
  /identities/{id}:
    get:
      description: Sample
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        type: string
      responses:
        200:
          description: OK
definitions:
  inline_response_200:
    properties:
      id:
        type: string
      name:
        type: string
